export const SIG_LOAD = 'SIG_LOAD';
export const SIG_LOAD_SUCCESS = 'SIG_LOAD_SUCCESS';
export const SIG_LOAD_ERROR = 'SIG_LOAD_ERROR';

export const SIG_CREATE = 'SIG_CREATE';
export const SIG_CREATE_SUCCESS = 'SIG_CREATE_SUCCESS';
export const SIG_CREATE_ERROR = 'SIG_CREATE_ERROR';

export const SIG_UPDATE = 'SIG_UPDATE';
export const SIG_UPDATE_SUCCESS = 'SIG_UPDATE_SUCCESS';
export const SIG_UPDATE_ERROR = 'SIG_UPDATE_ERROR';

export const SIG_UPDATE_ALL = 'SIG_UPDATE_ALL';
export const SIG_SET = 'SIG_SET';

export const SIGNATURE_TOGGLE_MODAL = 'SIGNATURE_TOGGLE_MODAL';
export const SIGNATURE_AUTO_SAVE = 'SIGNATURE_AUTO_SAVE';