pipeline {
    agent any
    stages {
        stage('Build') {
            agent {
                node {
                    label 'agent1'
                }
            }
            steps {
                echo 'Building..'
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
}