export const DOCUMENT_IS_DIRTY = 'IS_DIRTY';
export const DOCUMENT_START_UPLOAD = 'DOCUMENT_START_UPLOAD';
export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAILED = 'DOCUMENT_UPLOAD_FAILED';
export const DOCUMENT_UPLOAD_CANCEL = 'DOCUMENT_UPLOAD_CANCEL';
export const DOCUMENT_UPLOAD_PROGRESS = 'DOCUMENT_UPLOAD_PROGRESS';

