export const DOCUMENT_IS_DIRTY = 'IS_DIRTY';

export const DOCUMENT_UPLOAD_RENDER = 'DOCUMENT_UPLOAD_RENDER';

export const DOCUMENT_UPLOAD_FILES = 'DOCUMENT_UPLOAD_FILES';

export const DOCUMENT_UPLOAD_SUCCESS = 'DOCUMENT_UPLOAD_SUCCESS';
export const DOCUMENT_UPLOAD_FAILED = 'DOCUMENT_UPLOAD_FAILED';
export const DOCUMENT_UPLOAD_CANCEL = 'DOCUMENT_UPLOAD_CANCEL';
export const DOCUMENT_UPLOAD_CANCEL_ALL = 'DOCUMENT_UPLOAD_CANCEL_ALL';
export const DOCUMENT_UPLOAD_PROGRESS = 'DOCUMENT_UPLOAD_PROGRESS';

export const DOCUMENT_GET_ALL = 'DOCUMENT_GET_ALL';
export const DOCUMENT_GET_ALL_SUCCESS = 'DOCUMENT_GET_ALL_SUCCESS';
export const DOCUMENT_GET_ALL_FAILED = 'DOCUMENT_GET_ALL_FAILED';

export const DOCUMENT_GET_ONE = 'DOCUMENT_GET_ONE';
export const DOCUMENT_GET_ONE_SUCCESS = 'DOCUMENT_GET_ONE_SUCCESS';
export const DOCUMENT_GET_ONE_FAILED = 'DOCUMENT_GET_ONE_FAILED';

export const DOCUMENT_CREATE_CLONE = 'DOCUMENT_CREATE_CLONE';
export const DOCUMENT_CREATE_CLONE_SUCCESS = 'DOCUMENT_CREATE_CLONE_SUCCESS';
export const DOCUMENT_CREATE_CLONE_FAILED = 'DOCUMENT_CREATE_CLONE_FAILED';

export const DOCUMENT_GET_DETAIL = 'DOCUMENT_GET_DETAIL';