export const SET_CERT_DETAIL = 'SET_CERT_DETAIL'
export const GET_CERTIFICATE_ALL = 'GET_CERTIFICATES'
export const GET_CERTIFICATE_ALL_SUCCESS = 'GET_CERTIFICATE_ALL_SUCCESS'

export const CERTIFICANTS_UPDATE_ALL = 'UPDATE_ALL_CERTIFICANTS'
export const CERTIFICANT_SET = 'SET_CERTIFICANT'
export const CERTIFICANT_REMOVE = 'REMOVE_CERTIFICANT'

export const CERT_SIGNATURES_UPDATE_DATA = 'CERT_UPDATE_SIGNATURES_DATA'

export const SIGNATRURE_MOVE = 'CERT_MOVE_SIGNATRURE'

export const GET_ALL_CERTIFICANTS = 'GET_ALL_CERTIFICANTS'
export const GET_ALL_CERTIFICANTS_SUCCESS = 'GET_ALL_CERTIFICANTS_SUCCESS'
export const CLEAR_ALL_CERTIFICANTS = 'CLEAR_ALL_CERTIFICANTS'
export const CERT_SIGNATURES_CLEAR_ALL = 'CLEAR_ALL_SIGNATURES'

export const SET_SIGNER = 'CERT_SET_SIGNER'
export const SET_SIGNER_2 = 'CERT_SET_SIGNER_2'

export const CERT_SIGNATURE_SET = 'CERT_SET_SIGNATURE'
export const SIGNATURE_REMOVE = 'CERT_REMOVE_SIGNATURE'
export const SET_CERT_DETAIL_2 = 'SET_CERT_DETAIL_2'